services:

    shopery.i18n.router:
        class: 'Shopery\Bundle\I18nBundle\Routing\Router'
        arguments:
            - '@shopery.i18n.route_collector'
            - '@shopery.i18n.route_strategy'
            - '@shopery.i18n.cached_router_factory'
            - '@translator'
            - %shopery.i18n.available_languages%
            # Following parameters will be filled in compiler pass
            - null # context
        calls:
            - [ 'setRouteCache', [ '@shopery.i18n.route_cache' ] ]

    shopery.i18n.route_cache:
        class: 'Symfony\Component\Config\ConfigCacheInterface'
        factory: [ '@config_cache_factory', 'cache' ]
        arguments:
            - '%shopery.i18n.cache_dir%/routing.phpser'
            - [ '@shopery.i18n.router', 'setRouteCache' ]

    shopery.i18n.route_collector:
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\ResourceRouteCollector'
        arguments: ~

    shopery.i18n.resource_route_collector:
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\ResourceRouteCollector'
        decorates: 'shopery.i18n.route_collector'
        arguments:
            - '@routing.loader'
            # Following parameters will be filled in the compiler pass
            - null # resource
            - null # resource type

    shopery.i18n.resolver_route_collector:
        decorates: 'shopery.i18n.route_collector'
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\ResolverRouteCollector'
        arguments:
            - '@shopery.i18n.resolver_route_collector.inner'
            - '@service_container'

    shopery.i18n.prefixed_without_default_strategy:
        class: 'Shopery\Bundle\I18nBundle\Routing\RouteStrategy\PrefixedPathStrategy'

    shopery.i18n.route_strategy:
        alias: 'shopery.i18n.prefixed_without_default_strategy'

    shopery.i18n.cached_router_factory:
        class: 'Shopery\Bundle\I18nBundle\Routing\CachedRouterFactory'
        arguments:
            - '%shopery.i18n.cache_dir%/routing.d'
