services:

    shopery.i18n.router:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\Router'
        arguments:
            - '%shopery.i18n.available_languages%'
            - '@shopery.i18n.router_factory'
            - '@shopery.i18n.route_strategy'
            - null # context

    shopery.i18n.router_factory:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\CachedRouterFactory'
        arguments:
            - '%shopery.i18n.cache_dir%'
            - 'routing.d'

    shopery.i18n.route_strategy.prefixed_path_always:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\RouteStrategy\PrefixedPathStrategy'
        arguments: [ false ]

    shopery.i18n.route_strategy.prefixed_path_but_default:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\RouteStrategy\PrefixedPathStrategy'
        arguments: [ true ]

    shopery.i18n.route_collector:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\ResourceRouteCollector'
        arguments: ~

    shopery.i18n.resource_route_collector:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\ResourceRouteCollector'
        decorates: 'shopery.i18n.route_collector'
        arguments:
            - '@routing.loader'
            # Following parameters will be filled in the compiler pass
            - null # resource
            - null # resource type

    shopery.i18n.resolver_route_collector:
        public: false
        decorates: 'shopery.i18n.route_collector'
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\ResolverRouteCollector'
        arguments:
            - '@shopery.i18n.resolver_route_collector.inner'
            - '@service_container'

    shopery.i18n.locale_route_collector:
        public: false
        decorates: 'shopery.i18n.route_collector'
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\LocaleRouteCollector'
        arguments:
            - '@shopery.i18n.locale_route_collector.inner'
            - '@shopery.i18n.route_strategy'
            - '@shopery.i18n.router_factory'
            - '@translator'
            - '%shopery.i18n.available_languages%'

    shopery.i18n.cached_route_collector:
        public: false
        class: 'Shopery\Bundle\I18nBundle\Routing\Collector\CachedRouteCollector'
        arguments:
            - '@shopery.i18n.route_collector'
            - '@config_cache_factory'
            - '@shopery.i18n.router_factory'
            - '%shopery.i18n.cache_dir%'

    shopery.i18n.router_cache_warmer:
        public: false
        class: 'Shopery\Bundle\I18nBundle\CacheWarmer\RoutingCacheWarmer'
        arguments:
            - '@shopery.i18n.cached_route_collector'
        tags:
            - { name: kernel.cache_warmer }
